### ISSUE TITLE
Show message on the middle of the page and change message box width

### ISSUE THREAD

**Issue by lee-alex** [kunalnagar/jquery.peekABar#1]
Would you maybe add the possibility of placing the message box on the middle of the page? Also could you add an option to change the message box width? It would be great if it was possible to create customizable alert message boxes, maybe even with an ok-button.
Thank you very much for your work!

**Comment by kunalnagar** [comment]
@lee-alex I think there are other plugins that do this better. You can take a look at the [jQuery UI Dialog](https://jqueryui.com/dialog/) to begin with.
