### ISSUE TITLE
Custom Class Doesn't Work

### ISSUE THREAD

**Issue by teamayu** [kunalnagar/jquery.peekABar#147]
Great little plugin, thank you.

In the docs it says:

_"Assign a Custom CSS class to the bar. **Overrides ALL styles passed as options**. For e.g. padding, backgroundColor etc."_

This doesn't actually work as default parameters still get passed in which overwrite any custom class.

> var bar = $.peekABar({
    html         : 'Some message',
    delay        : 2000,
    autohide     : true,
    animation    : {
      type     : 'fade',
      duration : '2000'
    },
    opacity      : '0.8',
    cssClass     : 'bar-success',
    position     : 'bottom',
    closeOnClick : true,
    onShow       : function() {},
    onHide       : function() {}
  });
  bar.show();

This what is displayed in the dev console:

`<div` class="peek-a-bar bar-success" id="__peek_a_bar_48236846" style="padding: 1em; background-color: rgb(195, 195, 195); opacity: 0.8; bottom: 0px; display: none;">Some message</div>`

Padding and background are still applied as you are still setting them if the cssClass is not null. I updated the js code and it works fine now, but you may want to fix it. Inline styles overwrite the css.

**Comment by kunalnagar** [comment]
@teamayu - thanks for bringing this up. It is definitely a documentation issue - I'll fix it soon 👍
