### ISSUE TITLE
Where is jquery.peekabar.min.js.map

### ISSUE THREAD

**Issue by campones** [kunalnagar/jquery.peekABar#19]
Hello 

I get this when using the script

"DevTools failed to load SourceMap: Could not load content for https://www.example.com/templates/path/to/js/jquery.peekabar.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

what am I doing wrong?  

I m loading the files normally
/templates/path/to/js/jquery.peekabar.min.js
/templates/path/to/css/jquery.peekabar.min.css
thanks

**Comment by kunalnagar** [comment]
Hello @campones,

Thanks for using this library. In the source files you downloaded, there should be a `jquery.peekabar.min.js.map` file as well. If you put that in the same `js` folder, you should not get this warning.

**Comment by campones** [comment]
Yes I saw it now. I downloaded this a very long time ago .. I have version 1.0.1
And as I am not familiar with NPM I do not know how to upgrade. but this is okay for me. 

I saw the file and will put it on  my server

thanks for your work, it's great
