### ISSUE TITLE
Uncaught TypeError: $.peekABar is not a constructor

### ISSUE THREAD

**Issue by Isabellle** [kunalnagar/jquery.peekABar#2]
Thanks for this library, unfortunately I can't seem to be able to show the notification.
I put the js in the footer, just under jquery - does it need to be on top?

**Comment by kunalnagar** [comment]
It needs to be included after jQuery. How are you instantiating the library? You can try the following two ways:

```
var bar = new $.peekABar(options);
```

or

```
var bar = $.peekABar(options);
```

**Comment by Isabellle** [comment]
Thank you for the follow up. I'm using `var bar = new $.peekABar(options);`

**Comment by kunalnagar** [comment]
Here's a JSFiddle for your troubles: https://jsfiddle.net/kunalnagar/97v165pd/
